version: '3'

services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    depends_on:
     - postgres
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: postgres
            user: prisma
            password: prisma
            rawAccess: true
            port: 5432
            migrations: true

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    restart: always
    environment:
     - PRISMA_MANAGEMENT_API_SECRET=my-secret
    depends_on:
     - prisma
     - postgres
    ports:
     - 4000:4000
     - 5000:5000

  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    restart: always
    ports:
     - 3000:80

volumes:
  postgres:

